spring.application.name=fileHandling

server.port=8081

# File upload size config
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Custom upload directory
file.upload-dir=uploads